a = '''[{
        "AWB_NUMBER": "107249072",
        "ORDER_NUMBER": "107249072-001",
        "PRODUCT": "PPD",
        "CONSIGNEE": "Test API User",
        "CONSIGNEE_ADDRESS1": "H. No. A10",
        "CONSIGNEE_ADDRESS2": "Block-T",
        "CONSIGNEE_ADDRESS3": "Sector 39 Test",
        "DESTINATION_CITY": "GURGAON",
        "PINCODE": "111111",
        "STATE": "DL",
        "MOBILE": "1111111111",
        "TELEPHONE": "0123456789",
        "ITEM_DESCRIPTION": "Kids Bicycle",
        "PIECES": 1,
        "COLLECTABLE_VALUE": 0,
        "DECLARED_VALUE": 1000.0,
        "ACTUAL_WEIGHT": 0.5,
        "VOLUMETRIC_WEIGHT": 0,
        "LENGTH": 12,
        "BREADTH": 5,
        "HEIGHT": 2,
        "PICKUP_NAME": "Pickup Name 1",
        "PICKUP_ADDRESS_LINE1": "Pickup Addr ",
        "PICKUP_ADDRESS_LINE2": "Pickup Addr ",
        "PICKUP_PINCODE": "111111",
        "PICKUP_PHONE": "0123456789",
        "PICKUP_MOBILE": "1234567891",
        "RETURN_NAME": "Test Return Name 1",
        "RETURN_ADDRESS_LINE1": "Test Return ",
        "RETURN_ADDRESS_LINE2 ": "Test Return ",
        "RETURN_PINCODE": "111111",
        "RETURN_PHONE": "1111111111",
        "RETURN_MOBILE": "0123456789",
        "ADDONSERVICE": [""],
        "DG_SHIPMENT": "false",
        "ADDITIONAL_INFORMATION": {
                "essentialProduct": "Y",
                "OTP_REQUIRED_FOR_DELIVERY": "Y",
                "DELIVERY_TYPE": "",
                "SELLER_TIN": "SELLER_TIN_1234",
                "INVOICE_NUMBER": "INVOICE_1234",
                "INVOICE_DATE": "09-06-2018",
                "ESUGAM_NUMBER": "eSUGAM_1234",
                "ITEM_CATEGORY": "ELECTRONICS",
                "PACKING_TYPE": "Box",
                "PICKUP_TYPE": "WH",
                "RETURN_TYPE": "WH",
                "CONSIGNEE_ADDRESS_TYPE": "WH",
                "PICKUP_LOCATION_CODE": "PICKUP_ADDR_002",
                "SELLER_GSTIN": "GISTN988787",
                "GST_HSN": "123456",
                "GST_ERN": "123456789123",
                "GST_TAX_NAME": "DELHI GST",
                "GST_TAX_BASE": 900.0,
                "DISCOUNT": 0.0,
                "GST_TAX_RATE_CGSTN": 5.0,
                "GST_TAX_RATE_SGSTN": 5.0,
                "GST_TAX_RATE_IGSTN": 0.0,
                "GST_TAX_TOTAL": 100.0,
                "GST_TAX_CGSTN": 50.0,
                "GST_TAX_SGSTN": 50.0,
                "GST_TAX_IGSTN": 0.0
        }
}]
'''
